
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jan 15 2025 10:36:24 -03 (Jan 15 2025 13:36:24 UTC)

// Verification Directory fv/somador 

module somador(clk, rst_n, carry_i, a_i, b_i, carry_o, sum_o);
  input clk, rst_n, carry_i;
  input [7:0] a_i, b_i;
  output carry_o;
  output [7:0] sum_o;
  wire clk, rst_n, carry_i;
  wire [7:0] a_i, b_i;
  wire carry_o;
  wire [7:0] sum_o;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  DFFRHQX8 \sum_temp_reg[8] (.RN (rst_n), .CK (clk), .D (n_14), .Q
       (carry_o));
  DFFRHQX8 \sum_temp_reg[7] (.RN (rst_n), .CK (clk), .D (n_15), .Q
       (sum_o[7]));
  ADDFX1 g512__2398(.A (a_i[7]), .B (b_i[7]), .CI (n_12), .CO (n_14),
       .S (n_15));
  DFFRHQX8 \sum_temp_reg[6] (.RN (rst_n), .CK (clk), .D (n_13), .Q
       (sum_o[6]));
  ADDFX1 g514__5107(.A (a_i[6]), .B (b_i[6]), .CI (n_10), .CO (n_12),
       .S (n_13));
  DFFRHQX8 \sum_temp_reg[5] (.RN (rst_n), .CK (clk), .D (n_11), .Q
       (sum_o[5]));
  ADDFX1 g516__6260(.A (a_i[5]), .B (b_i[5]), .CI (n_8), .CO (n_10), .S
       (n_11));
  DFFRHQX8 \sum_temp_reg[4] (.RN (rst_n), .CK (clk), .D (n_9), .Q
       (sum_o[4]));
  ADDFX1 g518__4319(.A (a_i[4]), .B (b_i[4]), .CI (n_6), .CO (n_8), .S
       (n_9));
  DFFRHQX8 \sum_temp_reg[3] (.RN (rst_n), .CK (clk), .D (n_7), .Q
       (sum_o[3]));
  ADDFX1 g520__8428(.A (a_i[3]), .B (b_i[3]), .CI (n_4), .CO (n_6), .S
       (n_7));
  DFFRHQX8 \sum_temp_reg[2] (.RN (rst_n), .CK (clk), .D (n_5), .Q
       (sum_o[2]));
  ADDFX1 g522__5526(.A (a_i[2]), .B (b_i[2]), .CI (n_2), .CO (n_4), .S
       (n_5));
  DFFRHQX8 \sum_temp_reg[1] (.RN (rst_n), .CK (clk), .D (n_3), .Q
       (sum_o[1]));
  ADDFX1 g524__6783(.A (a_i[1]), .B (b_i[1]), .CI (n_0), .CO (n_2), .S
       (n_3));
  DFFRHQX8 \sum_temp_reg[0] (.RN (rst_n), .CK (clk), .D (n_1), .Q
       (sum_o[0]));
  ADDFX1 g526__3680(.A (carry_i), .B (a_i[0]), .CI (b_i[0]), .CO (n_0),
       .S (n_1));
endmodule

